name: build-image

on:
  workflow_dispatch:

env:
  ORG: ${{ secrets.DOCKERHUB_USERNAME }}
    
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Inspect manifest image
        run: |
          echo 'manifest<<EOF' >>$GITHUB_ENV
          echo "$(docker manifest inspect -v ${{ secrets.DOCKERHUB_USERNAME }}/gentoo-stage3)" >>$GITHUB_ENV
          echo 'EOF' >>$GITHUB_ENV
      - name: Eval platforms from manifest
        uses: actions/github-script@v3
        id: eval-platforms
        with:
          script: |
            const manifestList=process.env.manifest
            const platformList=manifestList.map(manifest=>manifest.Descriptor.platform)
            console.log(`And the manifest is: ${platformList}`)
      - name: Available image platforms
        run: |
          echo "${{toJSON(fromJSON(env.manifest).*.Descriptor.platform)}}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: context
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gentoo-stage4
