name: build-image

on:
  workflow_dispatch:

env:
  ORG: ${{ secrets.DOCKERHUB_USERNAME }}
    
jobs:
  detect-platforms:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.eval-platforms.outputs.result }}
    steps:
      - name: Inspect manifest image
        run: |
          echo 'manifest<<EOF' >>$GITHUB_ENV
          echo "$(docker manifest inspect -v ${{ secrets.DOCKERHUB_USERNAME }}/gentoo-stage3)" >>$GITHUB_ENV
          echo 'EOF' >>$GITHUB_ENV
      - name: Available image platforms
        run: |
          echo "${{toJSON(fromJSON(env.manifest).*.Descriptor.platform)}}"
      - name: Eval platforms from manifest
        uses: actions/github-script@v3
        id: eval-platforms
        with:
          script: |
            const manifestList=JSON.parse(process.env.manifest)
            console.log('manifestList is of type: '+(typeof manifestList))
            const platformList=manifestList.map(manifest=>manifest.Descriptor.platform)
            const platformStrList=platformList.map(platform=>(`${platform.os}/${platform.architecture}${(platform.variant!==null&&platform.variant!==undefined)?('/'+platform.variant):''}`))
            console.log(`And the manifest is: ${platformStrList}`)
            return `${platformStrList}`
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    needs: detect-platforms
    strategy:
      matrix:
        platform: ${{ needs.detect-platforms.outputs.platforms }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: context
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gentoo-stage4
