name: build-image

on:
  workflow_dispatch:

env:
  ORG: ${{ secrets.DOCKERHUB_USERNAME }}
  PREFIX: gentoo
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up workflow variables
        run: |
          ([[ ! -z "${PREFIX}" ]]&&echo "hasPREFIX=true"||echo "hasPREFIX=false") >>$GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: context
          push: true
